from __future__ import annotations

UI = {
    # App
    "app.title": "🐟 Aquantis",

    # Tabs
    "tab.daily": "Daily report",
    "tab.analytics": "Analytics",
    "tab.new_event": "New Event",
    "tab.incidents": "Active Incidents",
    "tab.reports": "Reports",
    "tab.settings": "Settings",

    # Generic actions
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.close": "Close",
    "action.submit": "Submit",
    "action.generate": "Generate",
    "action.refresh": "Refresh",
    "action.export_pdf": "Export PDF",
    "action.download": "Download",
    "action.add": "Add",
    "action.remove": "Remove",
    "action.search": "Search",

    # Generic statuses / messages
    "msg.no_data": "No data available.",
    "msg.saved": "Saved successfully.",
    "msg.updated": "Updated successfully.",
    "msg.deleted": "Deleted successfully.",
    "msg.error": "Something went wrong.",
    "msg.coming_soon": "Coming soon.",

    # Generic labels
    "label.date": "Date",
    "label.time": "Time",
    "label.status": "Status",
    "label.severity": "Severity",
    "label.notes": "Notes",
    "label.comments": "Comments",
    "label.species": "Species",
    "label.duration": "Duration",
    "label.mortality": "Mortality",
    "label.symptoms": "Symptoms",
    "label.farm": "Farm",
    "label.tank": "Tank",
    "label.system": "System",
    "label.operator": "Operator",

    # Settings
    "settings.title": "Settings",
    "settings.active_farm": "Active farm",

    "settings.button.set_active": "Set active",
    "settings.button.new_farm": "New farm",
    "settings.button.create": "Create",
    "settings.button.save_farm": "Save farm",
    "settings.button.delete_farm": "Delete farm",
    "settings.button.new_unit": "New unit",
    "settings.button.delete_unit": "Delete unit",
    "settings.button.save_unit": "Save unit",
    "settings.button.new_tank": "New tank",
    "settings.button.delete_tank": "Delete tank",

    "settings.create_farm.title": "Create farm",
    "settings.farm_detail.title": "Farm detail",
    "settings.units.title": "Units",
    "settings.tanks.title": "Tanks",
    "settings.water_parameters.title": "Water parameters (per unit)",
    "settings.water_parameters.caption": "Only active parameters will be used in Daily report.",
    "settings.o2_per_tank.title": "O2 per tank",

    "settings.field.farm_name": "Farm name",
    "settings.field.operation": "Operation",
    "settings.field.species_pack": "Species pack",
    "settings.field.custom_species": "Custom species",
    "settings.field.unit_name": "Unit name",
    "settings.field.tank_name": "Tank name",
    "settings.field.biomass_kg": "Biomass (kg)",
    "settings.field.avg_weight_g": "Avg weight (g)",
    "settings.field.feed_kg_day": "Feed kg per day",

    "settings.table.parameter": "Parameter",
    "settings.table.set_active": "Set active",
    "settings.table.min": "Min",
    "settings.table.target": "Target",
    "settings.table.max": "Max",

    "settings.unit.fallback_name": "Unit",
    "settings.tank.fallback_name": "Tank",

    "settings.msg.fill_farm_name": "Fill Farm name.",
    "settings.msg.no_farms": "No farms yet. Click **New farm**.",
    "settings.msg.no_units": "No units yet. Click **New unit**.",
    "settings.msg.no_tanks": "No tanks yet. Click **New tank**.",
    "settings.msg.farm_saved": "Farm saved.",
    "settings.msg.unit_saved": "Unit saved.",
    "settings.msg.deleted": "Deleted.",

    # Today / Daily report
    "today.title": "Daily report",
    "today.field.unit": "Unit",

    "today.measurements.title": "Measurements",
    "today.tanks.title": "Tanks",
    "today.o2_summary.title": "O2 summary",
    "today.risk_level.title": "Risk Level",
    "today.top_risks.title": "Top risks",
    "today.checklist.title": "Checklist",
    "today.signals.title": "Signals",
    "today.last_7_days.title": "Last 7 days",

    "today.button.reset_form": "Reset form",

    "today.table.biomass_kg": "Biomass (kg)",
    "today.table.avg_weight_g": "Avg wt (g)",
    "today.table.feed_kg_day": "Feed - kg/day",
    "today.table.o2": "O2",
    "today.table.mortality": "Mortality",

    "today.metric.lowest_o2": "Lowest O2",
    "today.metric.average_o2": "Average O2",
    "today.metric.o2_spread": "O2 spread",
    "today.metric.planned_feed_kg_day": "Planned feed kg/day",
    "today.metric.mortality_total": "Mortality total",
    "today.metric.tanks": "Tanks",

    "today.msg.no_farms": "No farms found.",
    "today.msg.go_settings_create_farm": "Go to Settings → create farm.",
    "today.msg.no_units": "No units in this farm.",
    "today.msg.go_settings_create_unit": "Go to Settings → create unit.",
    "today.msg.today_loaded": "Today's report loaded. You can edit values and press Save again to update today's report.",
    "today.msg.no_active_unit_params": "No active unit parameters. Go to Settings → Unit → Set active.",
    "today.msg.no_tanks": "No tanks in this unit.",
    "today.msg.no_daily_logs": "No daily logs yet.",

    # Analytics
    "analytics.title": "Analytics",

    "analytics.field.range": "Range",
    "analytics.field.parameter": "Parameter",

    "analytics.parameter_chart.title": "Parameter chart",
    "analytics.mortality.title": "Mortality",
    "analytics.total_mortality_unit.title": "Total mortality (unit)",
    "analytics.mortality_tank.title": "Mortality",
    "analytics.o2_tank.title": "O2",

    "analytics.table.biomass_kg": "Biomass (kg)",
    "analytics.table.avg_weight_g": "Avg wt (g)",
    "analytics.table.feed_kg_day": "Feed - kg/day",
    "analytics.table.o2": "O2",
    "analytics.table.mortality": "Mortality",

    "analytics.metric.planned_feed_total": "Planned feed total",
    "analytics.metric.planned_feed_total_kg_day": "Planned feed total (kg/day)",
    "analytics.metric.mortality_total": "Mortality total",
    "analytics.metric.tanks": "Tanks",

    "analytics.msg.no_farms": "No farms found.",
    "analytics.msg.go_settings_create_farm": "Go to Settings → create farm.",
    "analytics.msg.no_daily_logs": "No daily logs yet.",
    "analytics.msg.no_units": "No units in this farm.",
    "analytics.msg.no_logs_for_selection": "No daily logs for selected farm/unit.",
    "analytics.msg.no_data_for_parameter": "No data for selected parameter.",
    "analytics.msg.parameter_not_found": "Selected parameter not found in daily logs.",
    "analytics.msg.no_mortality_data": "No mortality data yet.",
    "analytics.msg.no_tank_level_data": "No tank-level data yet.",

    # Analytics PDF
    "analytics.pdf.daily_report": "Daily report",
    "analytics.pdf.no_major_issues": "No major issues flagged.",
    "analytics.pdf.continue_monitoring": "Continue routine monitoring.",
    "analytics.pdf.executive_summary": "Executive summary",
    "analytics.pdf.risk_level": "Risk level",
    "analytics.pdf.main_issues": "Main issues",
    "analytics.pdf.recommendation": "Recommendation",
    "analytics.pdf.operational_snapshot": "Operational snapshot",
    "analytics.pdf.timestamp_utc": "Timestamp (UTC)",
    "analytics.pdf.water_quality_summary": "Water quality summary",
    "analytics.pdf.tank_summary": "Tank summary",
    "analytics.pdf.top_risks_and_signals": "Top risks and signals",
    "analytics.pdf.checklist_followup": "Checklist / recommended follow-up",
    "analytics.pdf.appendix": "Appendix",
    "analytics.pdf.generated_utc": "Generated (UTC)",

    # Reports
    "reports.title": "Reports",

    "reports.field.period": "Period",
    "reports.field.open_daily_record": "Open daily record",

    "reports.period.7_days": "7 days",
    "reports.period.30_days": "30 days",

    "reports.button.generate_weekly_pdf": "Generate Weekly PDF",
    "reports.button.generate_daily_pdf": "Generate Daily PDF",

    "reports.metric.logs": "Logs",
    "reports.metric.logs_reviewed": "Logs reviewed",
    "reports.metric.mortality_total": "Mortality total",
    "reports.metric.avg_o2_per_unit": "Avg O2 per unit",
    "reports.metric.avg_feed_day": "Avg feed/day",
    "reports.metric.planned_feed": "Planned feed",
    "reports.metric.planned_feed_total_kg_day": "Planned feed total (kg/day)",
    "reports.metric.total_feed_for_period": "Total feed for period",
    "reports.metric.high_risk_days": "High-risk days",
    "reports.metric.overall_status": "Overall status",
    "reports.metric.worst_day": "Worst day",
    "reports.metric.best_day": "Best day",
    "reports.metric.tanks": "Tanks",

    "reports.risk_overview.title": "Risk overview",
    "reports.top_repeated_risks.title": "Top repeated risks",
    "reports.observations.title": "Observations",
    "reports.daily_log_database.title": "Daily log database",
    "reports.day_detail.title": "Day detail",
    "reports.measurements.title": "Measurements",

    "reports.meta.date_utc": "Date (UTC)",
    "reports.meta.day": "Day",
    "reports.meta.risk": "Risk",
    "reports.meta.feed_total": "Feed total",
    "reports.meta.mortality_total": "Mortality total",
    "reports.meta.o2_min": "O2 min",
    "reports.meta.o2_avg": "O2 avg",

    "reports.table.biomass": "Biomass",
    "reports.table.avg_weight": "Avg weight",
    "reports.table.feed_kg_day": "Feed - kg/day",
    "reports.table.feed_pct_day": "Feed %/day",
    "reports.table.planned_feed_kg_day": "Planned feed kg/day",
    "reports.table.o2": "O2",
    "reports.table.mortality": "Mortality",

    "reports.status.elevated_operational_risk": "Elevated operational risk",
    "reports.status.watch_mortality_recorded": "Watch - mortality recorded during the period",
    "reports.status.stable_operations": "Stable operations",

    "reports.obs.mortality_recorded_last_days": "Mortality recorded during the last",
    "reports.obs.days": "days",
    "reports.obs.avg_o2_low": "Average O2 per unit is low and should be reviewed.",
    "reports.obs.most_frequent_issue": "Most frequent repeated issue this period",
    "reports.obs.high_risk_days_recorded": "High-risk days recorded during the period",
    "reports.obs.total_planned_feed_period": "Total planned feed during the period",

    "reports.msg.no_farms": "No farms found.",
    "reports.msg.go_settings_create_farm": "Go to Settings → create farm.",
    "reports.msg.no_daily_logs": "No daily logs yet.",
    "reports.msg.no_units": "No units in this farm.",
    "reports.msg.no_logs_for_selection": "No daily logs for selected farm/unit and period.",

    # Reports PDF
    "reports.pdf.daily_report": "Daily report",
    "reports.pdf.weekly_performance_report": "Weekly performance report",
    "reports.pdf.selected_period": "Selected period",
    "reports.pdf.no_major_issues": "No major issues flagged.",
    "reports.pdf.no_major_repeated_issue": "No major repeated issue identified.",
    "reports.pdf.continue_monitoring": "Continue routine monitoring.",
    "reports.pdf.executive_summary": "Executive summary",
    "reports.pdf.risk_level": "Risk level",
    "reports.pdf.main_issues": "Main issues",
    "reports.pdf.main_issue": "Main issue",
    "reports.pdf.recommendation": "Recommendation",
    "reports.pdf.management_takeaway": "Management takeaway",
    "reports.pdf.management_takeaway_default": "Continue routine monitoring and maintain current operating discipline.",
    "reports.pdf.recommendation_next_period": "Review the main repeated issue and confirm actions for the next reporting period.",
    "reports.pdf.operational_snapshot": "Operational snapshot",
    "reports.pdf.kpi_snapshot": "KPI snapshot",
    "reports.pdf.timestamp_utc": "Timestamp (UTC)",
    "reports.pdf.water_quality_summary": "Water quality summary",
    "reports.pdf.tank_summary": "Tank summary",
    "reports.pdf.top_risks_and_signals": "Top risks and signals",
    "reports.pdf.checklist_followup": "Checklist / recommended follow-up",
    "reports.pdf.losses_and_production_impact": "Losses and production impact",
    "reports.pdf.weekly_operational_interpretation": "Weekly operational interpretation",
    "reports.pdf.repeated_issues_observed": "Repeated issues observed",
    "reports.pdf.interpretation": "Interpretation",
    "reports.pdf.no_additional_interpretation": "No additional interpretation available.",
    "reports.pdf.action_plan_next_week": "Action plan for next week",
    "reports.pdf.recommended_priorities": "Recommended priorities",
    "reports.pdf.review_and_address_recurring_issue": "Review and address recurring issue",
    "reports.pdf.continue_monitoring_weekly_review": "Continue routine monitoring and weekly review.",
    "reports.pdf.key_events_timeline": "Key events timeline",
    "reports.pdf.no_key_events": "No key events identified for the selected period.",
    "reports.pdf.no_repeated_high_priority_issue": "No repeated high-priority issue was identified from the selected logs.",
    "reports.pdf.period": "Period",
    "reports.pdf.total_mortality_period_line": "Total mortality recorded during the period",
    "reports.pdf.total_planned_feed_period_line": "Total planned feed during the period",
    "reports.pdf.avg_daily_feed_line": "Average daily feed",
    "reports.pdf.avg_o2_period_line": "Average O2 per unit during the period",
    "reports.pdf.appendix": "Appendix",
    "reports.pdf.export_type": "Export type",
    "reports.pdf.generated_utc": "Generated (UTC)",

    # Incidents
    "incidents.title": "📁 Incidents",
    "incidents.filters.title": "Filters",
    "incidents.filters.only_open": "Show only OPEN",
    "incidents.filters.search": "Search (ID/title/trigger)",
    "incidents.list.title": "List",
    "incidents.table.created_utc": "Created (UTC)",
    "incidents.table.id_title": "ID / Title",
    "incidents.table.action": "Action",
    "incidents.field.title": "Title",
    "incidents.field.workspace_status": "Workspace status",
    "incidents.button.open": "Open",
    "incidents.button.back_to_list": "← Back to list",
    "incidents.button.save_tasks": "Save tasks",
    "incidents.button.save_workflow": "Save workflow",
    "incidents.button.resolve": "Resolve",
    "incidents.button.reopen": "Re-open",
    "incidents.button.download_pdf": "Download PDF",
    "incidents.workspace.title": "Workspace",
    "incidents.tasks.title": "Tasks",
    "incidents.tasks.done": "Done",
    "incidents.tasks.fallback_group": "Tasks",
    "incidents.timeline.title": "Timeline",
    "incidents.timeline.who": "Who",
    "incidents.timeline.log_entry": "Log entry",
    "incidents.timeline.quick.o2_checked": "O2 checked",
    "incidents.timeline.quick.no2_retest": "NO2 re-test",
    "incidents.timeline.quick.feeding_reduced": "Feeding reduced",
    "incidents.timeline.quick.biofilter_inspected": "Biofilter inspected",
    "incidents.inputs.title": "Inputs",
    "incidents.inputs.risk_bundle_snapshot": "Risk bundle snapshot",
    "incidents.workflow.title": "Workflow",
    "incidents.workflow.who_handled": "Who handled",
    "incidents.workflow.what_was_done": "What was done",
    "incidents.workflow.note": "Note",
    "incidents.audit.title": "Audit / History",
    "incidents.diagnostics.title": "Diagnostics",
    "incidents.diagnostics.probable_cause": "Primary probable cause (top 3) + confidence",
    "incidents.diagnostics.immediate_actions": "Immediate actions (0–30 min)",
    "incidents.diagnostics.stabilization": "Stabilization (2–24 h)",
    "incidents.diagnostics.tests_to_verify": "What to verify / additional tests",
    "incidents.diagnostics.escalation_thresholds": "When to escalate",
    "incidents.diagnostics.kb_sources": "KB sources",
    "incidents.diagnostics.rag_score": "RAG score",
    "incidents.msg.no_incidents": "No incidents yet.",
    "incidents.msg.no_match_filters": "No incidents match filters.",
    "incidents.msg.click_open_detail": "Click **Open** to view detail.",
    "incidents.msg.not_found": "Incident not found.",
    "incidents.msg.no_tasks": "No tasks yet.",
    "incidents.msg.no_timeline_entries": "No timeline entries.",
    "incidents.msg.resolved": "Resolved.",
    "incidents.msg.reopened": "Re-opened.",
    "incidents.msg.no_history_records": "No history records.",
    "incidents.msg.no_audit_trail": "No audit trail.",

    # Diagnostics
    "diagnostics.title": "Guided Diagnostics",
    "diagnostics.msg.no_farms": "No farms found. Go to Settings → create farm.",
    "diagnostics.msg.selected_farm_not_found": "Selected farm not found.",
    "diagnostics.msg.fill_custom_species": "Fill custom species.",
    "diagnostics.msg.fill_symptoms": "Fill symptoms.",
    "diagnostics.msg.analyzing": "Analyzing...",
    "diagnostics.msg.run_analyze_first": "Run Analyze first.",
    "diagnostics.msg.already_converted": "Already converted.",
    "diagnostics.msg.incident_created": "Incident created",

    "diagnostics.value.not_provided": "Not provided",

    "diagnostics.measurements.title": "Measurements",
    "diagnostics.measurement.temp": "Temp",
    "diagnostics.measurement.salinity": "Salinity",

    "diagnostics.button.analyze": "Analyze",
    "diagnostics.button.convert_to_incident": "Convert to Incident",

    "diagnostics.mortality.none": "No",
    "diagnostics.mortality.few": "Yes, a few fish",
    "diagnostics.mortality.tens": "Yes, tens of fish",
    "diagnostics.mortality.massive": "Yes, massive mortality",

    "diagnostics.duration.lt_6h": "< 6 hours",
    "diagnostics.duration.6_24h": "6–24 hours",
    "diagnostics.duration.1_3d": "1–3 days",
    "diagnostics.duration.gt_3d": "More than 3 days",

    "diagnostics.result.primary_cause": "Primary probable cause + confidence",
    "diagnostics.result.secondary_factors": "Contributing factors",
    "diagnostics.result.immediate_actions": "Immediate actions (0–30 min)",
    "diagnostics.result.stabilization": "Stabilization (2–24 h)",
    "diagnostics.result.tests_to_verify": "What to verify / additional tests",
    "diagnostics.result.escalation_thresholds": "When to escalate",

    "diagnostics.tasks.immediate_group": "Immediate (0–30 min)",
    "diagnostics.tasks.verify_group": "Verify / Tests",
    "diagnostics.tasks.stabilization_group": "Stabilization (2–24 h)",

    "diagnostics.incident.title_suffix": "Diagnostics",

    # PDF Report
    "pdf.executive_summary": "Executive summary",
    "pdf.timestamp_utc": "Timestamp (UTC)",
    "pdf.generated_utc": "Generated (UTC)",

    "pdf.incident.title": "Incident report",
    "pdf.incident.main_issue_fallback": "Incident under review",
    "pdf.incident.impact": "Impact",
    "pdf.incident.impact_fallback": "Operational impact not specified.",
    "pdf.incident.current_recommendation": "Current recommendation",
    "pdf.incident.current_recommendation_fallback": "Review incident details and continue monitoring.",
    "pdf.incident.context": "Incident context",
    "pdf.incident.incident_id": "Incident ID",
    "pdf.incident.symptoms_measurements": "Symptoms and measurements",
    "pdf.incident.diagnostic_conclusion": "Diagnostic conclusion",
    "pdf.incident.primary_probable_cause": "Primary probable cause",
    "pdf.incident.actions": "Actions",
    "pdf.incident.verify_tests": "Verify / tests",
    "pdf.incident.escalation": "Escalation",
    "pdf.incident.workspace": "Incident workspace",
    "pdf.incident.workflow_resolution": "Workflow and resolution",
    "pdf.incident.resolved_at_utc": "Resolved at (UTC)",
    "pdf.incident.audit_appendix": "Audit appendix",
    "pdf.incident.audit_trail": "Audit trail",
}


def t(key: str, default: str = "") -> str:
    """
    Return UI text by key.
    Falls back to `default` if provided, otherwise returns the key itself.
    """
    return UI.get(key, default or key)